name: gtk-bh-ads-4_3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - joblib
  - ipywidgets
  - jupyter
  - pip
  - setuptools<58
  - pip:
    - tpot
